Expose env, volume, and volume mounts in helm chart for the efs controller and deamonset
kubernetes-sigs/aws-efs-csi-driver pull request #1165
Opened 2023-10-18 18:43 UTC by cnmcavoy

**Is this a bug fix or adding new feature?**
New Feature

**What is this PR about? / Why do we need it?**
Allows configuring the EFS CSI Controller and Daemonset for IRSA in helm values without relying on the [IRSA webhook](https://github.com/aws/amazon-eks-pod-identity-webhook) being installed and configured in a cluster.

**What testing is done?** 
helm template produces the expected output.

2024-01-17 08:42 UTC, Helcaraxan commented
Would love to see this get merged. It would be really useful to inject IAM configuration for non-EKS clusters.

2024-04-19 19:29 UTC, seanzatzdev-amazon requested changes
Hi @cnmcavoy , please undo changes to the versions in charts/aws-efs-csi-driver/CHANGELOG.md and charts/aws-efs-csi-driver/Chart.yaml, as we update these values as part of our release process

2024-04-24 20:20 UTC, hazmat345 commented
+1 ... this would be very helpful

2024-04-25 13:48 UTC, slambrose commented
+1 , hoping this can get merged very soon.

2024-04-25 15:17 UTC, cnmcavoy commented
/remove-lifecycle stale

2024-05-01 13:25 UTC, slambrose commented
Is there an ETA for this?

2024-05-07 11:44 UTC, hazmat345 commented
This is currently a blocking issue for me - I need to use a different CA certificate bundle when talking to the AWS API in my environment. Until this feature is merged I have no way to overwrite the CA bundle in the controller pods with the updated bundle I need to use.

Would it help to create an issue to track this?

2024-05-09 13:32 UTC, slambrose commented
{{ ping }}

2024-05-21 11:42 UTC, hazmat345 commented
Issue created: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1349

2024-05-21 19:25 UTC, seanzatzdev-amazon approved these changes

2024-05-21 19:26 UTC, seanzatzdev-amazon commented
/lgtm

2024-05-21 19:28 UTC, merged