chore: Bump aws-sdk to 1.50 for EKS Pod Identity support
kubernetes-sigs/aws-efs-csi-driver pull request #1254
Opened 2024-01-25 00:00 UTC by askulkarni2

**Is this a bug fix or adding new feature?**
Bumps up aws-sdk-go to v1.50.3.

**What is this PR about? / Why do we need it?**

AWS SDK [v.1.47.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11) updated credential provider logic support which is required by pods which need to use the newly launched [Amazon EKS Pod Identities](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-eks-pod-identity/).

**What testing is done?** 

`make` and `make test`.

2024-04-04 18:03 UTC, seshank-sk commented
@justinsb any help to unblock this PR?

2024-04-10 15:33 UTC, aaroniscode commented
/ok-to-test

2024-04-19 18:35 UTC, seanzatzdev-amazon commented on vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
We need to leave the "vendor/k8s.io/kubernetes/" in front of these filepaths, otherwise e2e tests will fail locally.

2024-04-19 18:42 UTC, seanzatzdev-amazon requested changes
Please see the comments I left on vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go

2024-05-10 21:01 UTC, seanzatzdev-amazon approved these changes

2024-05-10 21:02 UTC, seanzatzdev-amazon commented
/lgtm

2024-05-10 21:46 UTC, merged