updated the k8s version and go
kubernetes-sigs/aws-efs-csi-driver pull request #957
Opened 2023-03-02 15:54 UTC by mskanth972

**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**

**What testing is done?**

2023-03-02 16:34 UTC, mskanth972 commented
/test pull-aws-efs-csi-driver-unit

2023-03-05 16:34 UTC, mskanth972 commented
/test pull-aws-efs-csi-driver-unit

2023-03-05 17:33 UTC, mskanth972 commented
/test pull-aws-efs-csi-driver-unit

2023-03-22 16:11 UTC, jsafrane requested changes

2023-03-22 16:11 UTC, jsafrane commented on go.mod
>  	k8s.io/kubelet v0.0.0 // indirect
v0.25.6

2023-03-22 16:11 UTC, jsafrane commented on go.mod
>  	k8s.io/csi-translation-lib v0.22.3 // indirect
v0.25.6

2023-03-22 16:11 UTC, jsafrane commented on go.mod
> +	k8s.io/utils v0.0.0-20221107191617-1a15be271d1d // indirect
v0.25.6

2023-05-16 04:32 UTC, mskanth972 commented on go.mod
>  	k8s.io/client-go v1.5.2
Done.

2023-05-16 04:34 UTC, mskanth972 commented on go.mod
>  	k8s.io/klog v1.0.0
Can you specify the library name which need to be v2.80.1?

2023-05-16 04:52 UTC, mskanth972 commented on go.mod
>  	k8s.io/klog v1.0.0
Done

2023-05-16 04:54 UTC, mskanth972 commented on go.mod
> +	k8s.io/utils v0.0.0-20221107191617-1a15be271d1d // indirect
Seems utils doesn't have release version.

2023-05-17 05:15 UTC, mskanth972 commented
/test pull-aws-efs-csi-driver-unit

2023-05-18 04:40 UTC, mskanth972 commented
/test pull-aws-efs-csi-driver-unit

2023-05-22 03:13 UTC, mskanth972 commented
/test pull-aws-efs-csi-driver-external-test-eks

2023-05-22 14:43 UTC, mskanth972 commented
/test pull-aws-efs-csi-driver-external-test-eks

2023-05-24 13:10 UTC, closed without merging